### ISSUE TITLE
TypeError: Cannot read property 'utc' of undefined

### ISSUE THREAD

**Issue by jhonjairoroa87** [urish/angular-moment#104]
I have just added angular-moment in my angularjs project and Im getting the error "TypeError: Cannot read property 'utc' of undefined"

In the following link I found out that the only option is to downgrade the momnetjs version: 

http://stackoverflow.com/questions/26642479/angular-moment-cannot-read-property-utc-of-undefined

"Apparently, since v2.4 moment is not a global object any more, which resulted in 'undefined' everytime angular-moment made a reference to moment.

I switch to v.2.3.1, it works like a charm now"

**Comment by urish** [comment]
Did you remember to include `moment.js` in your project?

**Comment by jhonjairoroa87** [comment]
Yes I did.

**Comment by jhonjairoroa87** [comment]
Yes I did.

**Comment by jhonjairoroa87** [comment]
Yes I did.

**Comment by urish** [comment]
So, if you could create a plunkr/jsfiddle that reproduces the issue that would be great. Thanks!

**Comment by murilomothsin** [comment]
I have the same error in my app.

I just change the order of includes and works fine!

<script src="app/assets/js/moment-with-locales.js"></script>
<script src="app/assets/js/angular-moment.min.js"></script>

**Comment by w9ahmed** [comment]
I'm having the same issue!

**Comment by EladBezalel** [comment]
i'm having the same problem, i'm including both moment.js and angular-moment

The problem seems to be that angular couldn't inject moment and its undefined

**Comment by w9ahmed** [comment]
@EladBezalel Are you sure about the import order?
import moment.js first and then angular-moment.

**Comment by EladBezalel** [comment]
Yes.. The order is fine..

**Comment by EladBezalel** [comment]
I figured out it was a problem with moment problem because its not working properly with node webkit.

**Comment by katrotz** [comment]
Same problem here. I use JSPM/SystemJS for package management/module loading.
moment is loaded in AMD format, while angular-moment is forced to global.

```
'format global';
/* global define */
'deps angular';
'deps moment';
```

which forces to load moment via global `angularMoment(angular, window.moment);` and in my case it is undefined. 

```
if (typeof define === 'function' && define.amd) {
		define(['angular', 'moment'], angularMoment);
	} else if (typeof module !== 'undefined' && module && module.exports) {
		angularMoment(angular, require('moment'));
		module.exports = 'angularMoment';
	} else {
		angularMoment(angular, window.moment);
	}
```

**Comment by EladBezalel** [comment]
My temporary solution is to install moment from npm and define it global:
```javascript
var moment = require('moment');
```

**Comment by urish** [comment]
Thanks for everyone who participated. This is now fixed and released as 0.10.1

**Comment by nikolai-b** [comment]
Just in case this helps someone else.
With release 0.10.1 I was still getting problems with this until I put
```html
< script src="moment/moment.js" > 
```
before angular.js (not just before angular moment).

**Comment by honitus** [comment]
Thanks @nikolai-b your tip fixed my issue.

@urish This issue needs to be re-opened.

**Comment by cmgustavo** [comment]
I had the same issue with nw.js (node-webkit). This was solved updating angular-moment to 0.10.1 and moment to 2.10.3. 

Thanks!

**Comment by Chalkin** [comment]
having same issue here.

using moment.js 2.10.3
angular-moment.js 0.10.1

I added angular-moment to my app.js in angular and added the angularMomentConfig
```
var app = angular.module('app', [
    'ui.router',
    'angularMoment'
])
.constant('angularMomentConfig', {
    preprocess: 'utc',
    timezone: 'Europe/Berlin'
})
``` 

regarding order, i have tried following orders (and others):

jquery.js
moment.js
moment-timezone.js
angular.js
angular-moment.js
app.js

jquery.js
moment.js
angular.js
angular-moment.js
app.js
moment-timezone.js


jquery.js
angular.js
app.js
moment.js
moment-timezone.js
angular-moment.js

and some more - same error all the time.

```
Uncaught SyntaxError: Unexpected reserved word
moment-timezone.js:22 Uncaught TypeError: Cannot read property 'tz' of undefined(anonymous function) @ moment-timezone.js:22VERSION @ moment-timezone.js:16(anonymous function) @ moment-timezone.js:18
angular.js:11655 TypeError: Cannot read property 'utc' of undefined
```

using it in my template and created at is a timestamp 1400054171:

```
{{ driverslog.created_at | amDateFormat:'dddd, MMMM Do YYYY, h:mm'}}
```

**Comment by faouzicaptivo** [comment]
@nikolai-b Thanks. i put  moment.js before Angular and works like a charm.

**Comment by mariowise** [comment]
I solve my problem with this versions

    "moment": "~2.11.2",
    "angular-moment": "1.0.0-beta.4",

**Comment by Rogerkael** [comment]
I solved my loading also the localization files bower_components/momentjs/min/moment-with-langs.min.js
